namespace BTDTool;

public enum _STATES
{
	FSM_LICENSEAGREEMENT,
	FSM_INIT,
	FSM_WAITFORDONGLE,
	FSM_GETDONGLEFWVERSION,
	FSM_CHOOSEDONGLE,
	FSM_DEVICESPECIFICFEATURES,
	FSM_SETTINGSDISPLAY,
	FSM_LOCALORREMOTE,
	FSM_LOCALCONFIRM,
	FSM_WAITFORREMOTE,
	FSM_SELECTFROMREMOTE,
	FSM_DOWNLOADFROMREMOTE,
	FSM_SYNCANDSTART,
	FSM_RP_START,
	FSM_RP_PRE_VALIDATE,
	FSM_RP_PRE_REBOOT,
	FSM_RP_POST_REBOOT,
	FSM_RP_POST_COMMIT,
	FSM_APP_CHECKPOINT,
	FSM_WAITFORRESP,
	FSM_WAITFORDONGLEREMOVAL,
	FSM_WAITFORRESPONSE,
	FSM_ERROR,
	FSM_ABORT,
	FSM_TERMINATE
}
