namespace BTDTool;

public enum U_OP
{
	UPGRADE_START_REQ = 1,
	UPGRADE_START_CFM = 2,
	UPGRADE_DATA_BYTES_REQ = 3,
	UPGRADE_DATA = 4,
	UPGRADE_ABORT_REQ = 7,
	UPGRADE_ABORT_CFM = 8,
	UPGRADE_TRANSFER_COMPLETE_IND = 11,
	UPGRADE_TRANSFER_COMPLETE_RES = 12,
	UPGRADE_PROCEED_TO_COMMIT = 14,
	UPGRADE_COMMIT_REQ = 15,
	UPGRADE_COMMIT_CFM = 16,
	UPGRADE_ERROR_IND = 17,
	UPGRADE_COMPLETE_IND = 18,
	UPGRADE_SYNC_REQ = 19,
	UPGRADE_SYNC_CFM = 20,
	UPGRADE_START_DATA_REQ = 21,
	UPGRADE_IS_VALIDATION_DONE_REQ = 22,
	UPGRADE_IS_VALIDATION_DONE_CFM = 23,
	UPGRADE_HOST_VERSION_REQ = 25,
	UPGRADE_HOST_VERSION_CFM = 26,
	UPGRADE_ERROR_RES = 31,
	INVALID_VALUE = 255
}
