namespace BTDTool;

public enum U_RESUMEPOINT
{
	UPGRADE_RESUME_POINT_START,
	UPGRADE_RESUME_POINT_PRE_VALIDATE,
	UPGRADE_RESUME_POINT_PRE_REBOOT,
	UPGRADE_RESUME_POINT_POST_REBOOT,
	UPGRADE_RESUME_POINT_POST_COMMIT
}
