namespace BTDTool;

public enum U_STATUS
{
	UPGRADE_STATUS_SUCCESS,
	UPGRADE_STATUS_UNEXPECTED_ERROR,
	UPGRADE_STATUS_ALREADY_CONNECTED_WARNING,
	UPGRADE_STATUS_IN_PROGRESS,
	UPGRADE_STATUS_BUSY,
	UPGRADE_STATUS_INVALID_POWER_STATE
}
