using System.Collections.Generic;

namespace BTDTool;

public static class UPM
{
	public static Dictionary<U_OP, string> OpDict;

	public static Dictionary<U_ERR, string> ErrorDict;

	static UPM()
	{
		OpDict = new Dictionary<U_OP, string>();
		OpDict.Add(U_OP.UPGRADE_START_REQ, "UPGRADE_START_REQ");
		OpDict.Add(U_OP.UPGRADE_START_CFM, "UPGRADE_START_CFM");
		OpDict.Add(U_OP.UPGRADE_DATA_BYTES_REQ, "UPGRADE_DATA_BYTES_REQ");
		OpDict.Add(U_OP.UPGRADE_DATA, "UPGRADE_DATA");
		OpDict.Add(U_OP.UPGRADE_ABORT_REQ, "UPGRADE_ABORT_REQ");
		OpDict.Add(U_OP.UPGRADE_ABORT_CFM, "UPGRADE_ABORT_CFM");
		OpDict.Add(U_OP.UPGRADE_TRANSFER_COMPLETE_IND, "UPGRADE_TRANSFER_COMPLETE_IND");
		OpDict.Add(U_OP.UPGRADE_TRANSFER_COMPLETE_RES, "UPGRADE_TRANSFER_COMPLETE_RES");
		OpDict.Add(U_OP.UPGRADE_PROCEED_TO_COMMIT, "UPGRADE_PROCEED_TO_COMMIT");
		OpDict.Add(U_OP.UPGRADE_COMMIT_REQ, "UPGRADE_COMMIT_REQ");
		OpDict.Add(U_OP.UPGRADE_COMMIT_CFM, "UPGRADE_COMMIT_CFM");
		OpDict.Add(U_OP.UPGRADE_ERROR_IND, "UPGRADE_ERROR_IND");
		OpDict.Add(U_OP.UPGRADE_COMPLETE_IND, "UPGRADE_COMPLETE_IND");
		OpDict.Add(U_OP.UPGRADE_SYNC_REQ, "UPGRADE_SYNC_REQ");
		OpDict.Add(U_OP.UPGRADE_SYNC_CFM, "UPGRADE_SYNC_CFM");
		OpDict.Add(U_OP.UPGRADE_START_DATA_REQ, "UPGRADE_START_DATA_REQ");
		OpDict.Add(U_OP.UPGRADE_IS_VALIDATION_DONE_REQ, "UPGRADE_IS_VALIDATION_DONE_REQ");
		OpDict.Add(U_OP.UPGRADE_IS_VALIDATION_DONE_CFM, "UPGRADE_IS_VALIDATION_DONE_CFM");
		OpDict.Add(U_OP.UPGRADE_HOST_VERSION_REQ, "UPGRADE_HOST_VERSION_REQ");
		OpDict.Add(U_OP.UPGRADE_HOST_VERSION_CFM, "UPGRADE_HOST_VERSION_CFM");
		OpDict.Add(U_OP.UPGRADE_ERROR_RES, "UPGRADE_ERROR_RES");
		ErrorDict = new Dictionary<U_ERR, string>();
		ErrorDict.Add(U_ERR.UPGRADE_HOST_SUCCESS, "UPGRADE_HOST_SUCCESS");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_OEM_VALIDATION_SUCCESS, "UPGRADE_HOST_OEM_VALIDATION_SUCCESS");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_DEPRECATED, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_DEPRECATED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_UNKNOWN_ID, "UPGRADE_HOST_ERROR_UNKNOWN_ID");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_DEPRECATED, "UPGRADE_HOST_ERROR_BAD_LENGTH_DEPRECATED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_WRONG_VARIANT, "UPGRADE_HOST_ERROR_WRONG_VARIANT");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_WRONG_PARTITION_NUMBER, "UPGRADE_HOST_ERROR_WRONG_PARTITION_NUMBER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_SIZE_MISMATCH, "UPGRADE_HOST_ERROR_PARTITION_SIZE_MISMATCH");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_TYPE_NOT_FOUND_DEPRECATED, "UPGRADE_HOST_ERROR_PARTITION_TYPE_NOT_FOUND_DEPRECATED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_OPEN_FAILED, "UPGRADE_HOST_ERROR_PARTITION_OPEN_FAILED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_WRITE_FAILED_DEPRECATED, "UPGRADE_HOST_ERROR_PARTITION_WRITE_FAILED_DEPRECATED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED_DEPRECATED, "UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED_DEPRECATED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_SFS_VALIDATION_FAILED, "UPGRADE_HOST_ERROR_SFS_VALIDATION_FAILED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_DEPRECATED, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_DEPRECATED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_UPDATE_FAILED, "UPGRADE_HOST_ERROR_UPDATE_FAILED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_APP_NOT_READY, "UPGRADE_HOST_ERROR_APP_NOT_READY");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_LOADER_ERROR, "UPGRADE_HOST_ERROR_LOADER_ERROR");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_UNEXPECTED_LOADER_MSG, "UPGRADE_HOST_ERROR_UNEXPECTED_LOADER_MSG");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_MISSING_LOADER_MSG, "UPGRADE_HOST_ERROR_MISSING_LOADER_MSG");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BATTERY_LOW, "UPGRADE_HOST_ERROR_BATTERY_LOW");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INVALID_SYNC_ID, "UPGRADE_HOST_ERROR_INVALID_SYNC_ID");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_IN_ERROR_STATE, "UPGRADE_HOST_ERROR_IN_ERROR_STATE");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_NO_MEMORY, "UPGRADE_HOST_ERROR_NO_MEMORY");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_SQIF_ERASE, "UPGRADE_HOST_ERROR_SQIF_ERASE");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_PARTITION_PARSE, "UPGRADE_HOST_ERROR_BAD_LENGTH_PARTITION_PARSE");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_TOO_SHORT, "UPGRADE_HOST_ERROR_BAD_LENGTH_TOO_SHORT");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_UPGRADE_HEADER, "UPGRADE_HOST_ERROR_BAD_LENGTH_UPGRADE_HEADER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_PARTITION_HEADER, "UPGRADE_HOST_ERROR_BAD_LENGTH_PARTITION_HEADER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_SIGNATURE, "UPGRADE_HOST_ERROR_BAD_LENGTH_SIGNATURE");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_BAD_LENGTH_DATAHDR_RESUME, "UPGRADE_HOST_ERROR_BAD_LENGTH_DATAHDR_RESUME");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_HEADERS, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_HEADERS");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_UPGRADE_HEADER, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_UPGRADE_HEADER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_PARTITION_HEADER1, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_PARTITION_HEADER1");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_PARTITION_HEADER2, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_PARTITION_HEADER2");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_PARTITION_DATA, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_PARTITION_DATA");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_FOOTER, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_FOOTER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_MEMORY, "UPGRADE_HOST_ERROR_OEM_VALIDATION_FAILED_MEMORY");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED, "UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED_HEADER, "UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED_HEADER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED_PS_SPACE, "UPGRADE_HOST_ERROR_PARTITION_CLOSE_FAILED_PS_SPACE");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_TYPE_NOT_MATCHING, "UPGRADE_HOST_ERROR_PARTITION_TYPE_NOT_MATCHING");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_TYPE_TWO_DFU, "UPGRADE_HOST_ERROR_PARTITION_TYPE_TWO_DFU");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_WRITE_FAILED_HEADER, "UPGRADE_HOST_ERROR_PARTITION_WRITE_FAILED_HEADER");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_PARTITION_WRITE_FAILED_DATA, "UPGRADE_HOST_ERROR_PARTITION_WRITE_FAILED_DATA");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_FILE_TOO_SMALL, "UPGRADE_HOST_ERROR_FILE_TOO_SMALL");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_FILE_TOO_BIG, "UPGRADE_HOST_ERROR_FILE_TOO_BIG");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_1, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_1");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_2, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_2");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_3, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_3");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_4, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_4");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_5, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_5");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_6, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_6");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_ERROR_INTERNAL_ERROR_7, "UPGRADE_HOST_ERROR_INTERNAL_ERROR_7");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_WARN_APP_CONFIG_VERSION_INCOMPATIBLE, "UPGRADE_HOST_WARN_APP_CONFIG_VERSION_INCOMPATIBLE");
		ErrorDict.Add(U_ERR.UPGRADE_HOST_WARN_SYNC_ID_IS_DIFFERENT, "UPGRADE_HOST_WARN_SYNC_ID_IS_DIFFERENT");
	}
}
